version: "3.8"
services:
  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: Dockerfile
    image: app
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      beanfun_pos_postgresql:
        condition: service_healthy
  postgresql:
    container_name: 
    image: postgres
    command: postgres -c 'max_connections=250'
    restart: always
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
      TZ: Asia/Taipei
    volumes:
      - ./data/postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
