version: "3.5"
services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    image: app
    ports:
      - "8080:8080"
    restart: always
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: test
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"